### ISSUE TITLE
Cause Invalid Content-Range header error when uploading a large file

### ISSUE THREAD

**Issue by hiroakit** [augustogoncalves/bucket.manager-csharp-sample.tool#12]
## Overview

Cause `error code: 416`  when uploading a large file.

```
Autodesk.Forge.Client.ApiException: 'Error calling UploadChunk: Invalid Content-Range header'
```

See also: [Definition status code](https://forge.autodesk.com/en/docs/data/v2/reference/http/buckets-:bucketKey-objects-:objectName-resumable-PUT/#http-status-code-summary)

## Steps to Reproduce the Problem

Getting the code.

```sh
git clone https://github.com/Autodesk-Forge/forge-bucketsmanager-desktop.git && forge-bucketsmanager-desktop
```

Make a 150 MB file.

```sh
dd if=/dev/random of=bigfile bs=1M count=150 
```

Do the following:

1. Open `bucket.manager.sln` with Visual Studio 2019 
1. Run x64 debugging
1. Enter credential information to the Bucket Manager
1. Success Authorization
1. Select bucket
1. Upload file, chose 150 MB file

## Additional Context

Operating System

- Windows 10 Pro x64 version 1909

Screenshots

![fig2](https://user-images.githubusercontent.com/359823/78775345-078c9180-79d1-11ea-835e-65d07f5dda6f.png)

![fig1](https://user-images.githubusercontent.com/359823/78775346-08252800-79d1-11ea-8cdb-e9029920d56a.png)

**Comment by hiroakit** [comment]
It's not a good idea to leave this task alone, as this application is introduced below.
https://stackoverflow.com/a/52894942/13257344

**Comment by dukedhx** [comment]
@hiroakit it'd be nice for the app to support chunked upload in the future and we'd try to make that happen soon as we can - in the meantime pls try the endpoint suggested in my answer to your SO question to upload larger files.

**Comment by josepsalom** [comment]
Hi,
 Yesterdar I uploaded 400mb file file out any trouble. It'as a IFC file.
Region:EMEA

**Comment by hiroakit** [comment]
Hi, guys.

This ticket has old information.
And I have already distanced myself from this issue. Please issue a separate ticket if necessary.
