### ISSUE TITLE
Potential endless loop?

### ISSUE THREAD

**Issue by petrbroz** [augustogoncalves/bucket.manager-csharp-sample.tool#13]
Looking at the following line of code:

https://github.com/Autodesk-Forge/forge-bucketsmanager-desktop/blob/3a6663fe9ce13338bbdfeba9fc3e1d9771b18284/bucket.manager/Form1.cs#L131

The while-loop seems to be running for as long as the "division remainder after dividing the number of buckets by 100 is zero". But, if there is actually zero buckets for a given Forge application, wouldn't this while-loop run forever?

**Comment by augustogoncalves** [comment]
agree, that pagination would need some improvement...
