### ISSUE TITLE
model converted only 2D

### ISSUE THREAD

**Issue by dbste71** [augustogoncalves/bucket.manager-csharp-sample.tool#5]
Good evening,
I have download this project. All is working in your code. I am very happy wy it's first time that i use FORGE with C#.

I have only a issue with conversion file.
This is my steps (after my authentication):
1) I have create a DWG  file with only a simple 3D BOX;
2) I have upload this file DWG;
3)I have press "Translate file" and then " and then i have press "Viewer SVS"

In the viewer i see only a box 2D model. 
There isn't model 3D. 
Then there isnt't cube navigator 3D on top right of window. There is only home view.
I think that i am seeing only a 2d Viewer.

Wy ? There is a issue on conversion file ?

Thanks in advance for your reply

Stefano M.

**Comment by dukedhx** [comment]
That's probably because by default the manager loads the default view which happened to be the 2d view of your design file.

We are working to upgrade Viewer to v7 so you'd be able to browse all available views and choose which to load
