### ISSUE TITLE
An error occurred in the program

### ISSUE THREAD

**Issue by www963257827** [augustogoncalves/bucket.manager-csharp-sample.tool#6]
I opened the sln file and the form program after using visual studio 2015 and 2015 versions. After inputting ID and secret, I clicked Authenticate button to here comes an error
![image](https://user-images.githubusercontent.com/49772139/69594921-d1113400-1038-11ea-879f-5f60f6976a5f.png)

**Comment by augustogoncalves** [comment]
Can you try with a newer Visual Studio? 2015 version is no longer supported with recent .NET versions.
